IMPORTS E CONEXAO COM O BANCO

In [3]:
import pandas as pd

from sqlalchemy import create_engine

motor = create_engine(
    "postgresql+psycopg2://postgres:p0stgr3$@localhost:5432/bolsa_familia"
)

CARREGAR ARQUIVOS

In [2]:
saques = pd.read_csv(
    "../geralSaqueBolsaF.csv"
)

dependentes = pd.read_csv(
    "../dependentesPorNISTrue_.csv"
)

municipio_resumo = pd.read_csv(
    "../bolsafamiliaMunicipio.csv"
)

MUNICÍPIOS

In [3]:
municipios = (
    saques[
        ["Nome IBGE"]
    ]
    .drop_duplicates()
    .rename(
        columns={
            "Nome IBGE": "nome"
        }
    )
)

municipios.to_sql(
    "municipios",
    motor,
    if_exists="append",
    index=False
)

print(
    "Municípios:",
    len(municipios)
)

Municípios: 5

BENEFICIÁRIOS

In [4]:
municipios_db = pd.read_sql(
    """
    select
        id,
        nome
    from municipios
    """,
    motor
)

beneficiarios = (
    saques[
        [
            "NIS",
            "Nome",
            "Nome IBGE"
        ]
    ]
    .drop_duplicates()
)

beneficiarios = beneficiarios.merge(
    municipios_db,
    left_on="Nome IBGE",
    right_on="nome",
    how="inner"
)

beneficiarios = beneficiarios.merge(
    dependentes[
        [
            "NIS",
            "Quantidade de Dependentes"
        ]
    ],
    on="NIS",
    how="left"
)

beneficiarios[
    "Quantidade de Dependentes"
] = (
    beneficiarios[
        "Quantidade de Dependentes"
    ]
    .fillna(0)
)

beneficiarios = beneficiarios[
    [
        "NIS",
        "Nome",
        "id",
        "Quantidade de Dependentes"
    ]
]

beneficiarios.columns = [
    "nis",
    "nome",
    "municipio_id",
    "quantidade_dependentes"
]

beneficiarios = (
    beneficiarios
    .sort_values("nis")
    .drop_duplicates(
        subset=["nis"],
        keep="first"
    )
)

print(
    beneficiarios["nis"].duplicated().sum()
)

print(
    len(beneficiarios)
)

print(
    beneficiarios["nis"].nunique()
)

0
68821
68821

INSERIR BENEFICIÁRIOS

In [5]:
beneficiarios.to_sql(
    "beneficiarios",
    motor,
    if_exists="append",
    index=False
)

print(
    "Beneficiários carregados"
)

Beneficiários carregados

PAGAMENTOS

In [6]:
beneficiarios_db = pd.read_sql(
    """
    select
        id,
        nis
    from beneficiarios
    """,
    motor
)

beneficiarios_db["nis"] = (
    beneficiarios_db["nis"]
    .astype(str)
)

pagamentos = saques[
    [
        "NIS",
        "Data Referência",
        "Valor do Saque"
    ]
].copy()

pagamentos["NIS"] = (
    pagamentos["NIS"]
    .astype(str)
)

pagamentos = pagamentos.merge(
    beneficiarios_db,
    left_on="NIS",
    right_on="nis",
    how="inner"
)

pagamentos = pagamentos[
    [
        "id",
        "Data Referência",
        "Valor do Saque"
    ]
]

pagamentos.columns = [
    "beneficiario_id",
    "data_referencia",
    "valor_saque"
]

pagamentos["data_referencia"] = pd.to_datetime(
    pagamentos["data_referencia"],
    format="%m/%Y"
)

pagamentos["valor_saque"] = (
    pagamentos["valor_saque"]
    .astype(float)
)

print(pagamentos.info())
print(len(pagamentos))

<class 'pandas.DataFrame'>
RangeIndex: 1784480 entries, 0 to 1784479
Data columns (total 3 columns):
 #   Column           Dtype
---  ------           -----
 0   beneficiario_id  int64
 1   data_referencia  datetime64[us]
 2   valor_saque      float64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 40.8 MB
None
1784480

INSERIR PAGAMENTOS

In [7]:
pagamentos.to_sql(
    "pagamentos",
    motor,
    if_exists="append",
    index=False,
    chunksize=10000
)

print(
    "Pagamentos carregados"
)

Pagamentos carregados

FATO MUNICÍPIO

In [4]:
municipio_resumo = pd.read_csv(
    "../bolsafamiliaMunicipio.csv"
)

municipio_resumo.head()

   Nome IBGE Data Referência  Valor em R$  Nº de Beneficiários
0  ARAGUAÍNA         01/2019     944755.0                 7217
1  ARAGUAÍNA         02/2019     954282.0                 7284
2  ARAGUAÍNA         03/2019     959669.0                 7380
3  ARAGUAÍNA         04/2019     958023.0                 7395
4  ARAGUAÍNA         05/2019     966416.0                 7474

In [5]:
print(pd.read_sql(
    "select count(*) from municipios",
    motor
))

print(pd.read_sql(
    "select count(*) from beneficiarios",
    motor
))

print(pd.read_sql(
    "select count(*) from pagamentos",
    motor
))

   count
0      5
   count
0  68821
     count
0  1784480

In [6]:
municipio_resumo = pd.read_csv(
    "../bolsafamiliaMunicipio.csv"
)

municipios_db = pd.read_sql(
    """
    select
        id,
        nome
    from municipios
    """,
    motor
)

municipio_resumo = municipio_resumo.merge(
    municipios_db,
    left_on="Nome IBGE",
    right_on="nome",
    how="inner"
)

fato_municipio = municipio_resumo[
    [
        "id",
        "Data Referência",
        "Valor em R$",
        "Nº de Beneficiários"
    ]
].copy()

fato_municipio.columns = [
    "municipio_id",
    "data_referencia",
    "valor_total",
    "quantidade_beneficiarios"
]

fato_municipio["data_referencia"] = pd.to_datetime(
    fato_municipio["data_referencia"],
    format="%m/%Y"
)

print(fato_municipio.info())

fato_municipio.head()

<class 'pandas.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   municipio_id              315 non-null    int64
 1   data_referencia           315 non-null    datetime64[us]
 2   valor_total               315 non-null    float64
 3   quantidade_beneficiarios  315 non-null    int64
dtypes: datetime64[us](1), float64(1), int64(2)
memory usage: 10.0 KB
None

   municipio_id data_referencia  valor_total  quantidade_beneficiarios
0             1      2019-01-01     944755.0                      7217
1             1      2019-02-01     954282.0                      7284
2             1      2019-03-01     959669.0                      7380
3             1      2019-04-01     958023.0                      7395
4             1      2019-05-01     966416.0                      7474

In [8]:
fato_municipio.to_sql(
    "fato_municipio",
    motor,
    if_exists="append",
    index=False
)

315